/**
 * Licensing and Device ID / 30-Day Free Trial & Activation Service
 * 
 * 1. Generates a persistent unique hardware/device installation ID (e.g. MAR-8F2B-4A10)
 *    derived from physical device specs so it remains identical across uninstalls/reinstalls.
 * 2. Provides 30-Day (1 Month) Full Free Trial from first launch.
 * 3. After 30 days, enforces software activation key requirement.
 * 4. Verifies cryptographic/hash-based license codes generated by Developer.
 */

const LICENSE_STORAGE_KEY = 'mariner_license_key_v1';
const DEVICE_ID_STORAGE_KEY = 'mariner_device_id_v1';
const FIRST_INSTALL_KEY = 'mariner_first_install_ts_v1';
const DEVELOPER_FLAG_KEY = 'mariner_dev_mode_enabled_v1';

// Developer Master Secret (used for mathematical hash derivation)
const MASTER_SALT = 'MARINER_PRO_NAV_SALT_2026_SECRET_KEY';

// Master password fallback
export const DEVELOPER_PASSCODE = '2450';

// Official Application Support Email for License Requests
export const OFFICIAL_SUPPORT_EMAIL = 'Mariner-pro-link@proton.me';

// Developer Google Email list for instant auto-unlock via Google Account
export const DEVELOPER_GOOGLE_EMAILS = [
  'majid.nikbin@gmail.com',
  'mariner-pro-link@proton.me'
];

const GOOGLE_USER_STORAGE_KEY = 'mariner_google_user_v1';
const AUTO_DEV_UNLOCKED_KEY = 'mariner_dev_auto_unlocked_v1';

// 30 Days Trial Duration in Milliseconds (30 days * 24h * 60m * 60s * 1000ms)
export const TRIAL_DURATION_MS = 30 * 24 * 60 * 60 * 1000;

export interface GoogleUserProfile {
  email: string;
  name?: string;
  picture?: string;
  isDeveloper: boolean;
}

export interface LicenseStatus {
  isActivated: boolean;
  isTrialActive: boolean;
  isTrialExpired: boolean;
  daysRemaining: number;
  trialTotalDays: number;
  deviceId: string;
  activatedKey?: string;
  activatedAt?: string;
  firstInstallDate: string;
}

/**
 * Checks if the given email belongs to the developer
 */
export function isDeveloperEmail(email: string): boolean {
  if (!email) return false;
  const cleanEmail = email.trim().toLowerCase();
  return DEVELOPER_GOOGLE_EMAILS.some(e => e.toLowerCase() === cleanEmail);
}

/**
 * Gets the saved Google profile from storage
 */
export function getSavedGoogleUser(): GoogleUserProfile | null {
  try {
    const raw = localStorage.getItem(GOOGLE_USER_STORAGE_KEY);
    if (raw) return JSON.parse(raw);
  } catch {}
  return null;
}

/**
 * Saves Google profile and if it belongs to Developer, activates the app permanently
 */
export function saveGoogleUser(profile: { email: string; name?: string; picture?: string }): { isDeveloper: boolean } {
  const cleanEmail = profile.email.trim().toLowerCase();
  const isDev = isDeveloperEmail(cleanEmail);
  
  const userProfile: GoogleUserProfile = {
    email: cleanEmail,
    name: profile.name,
    picture: profile.picture,
    isDeveloper: isDev
  };

  try {
    localStorage.setItem(GOOGLE_USER_STORAGE_KEY, JSON.stringify(userProfile));
    if (isDev) {
      const deviceId = getOrCreateDeviceId();
      const devKey = generateActivationCode(deviceId);
      localStorage.setItem(LICENSE_STORAGE_KEY, devKey);
      localStorage.setItem(DEVELOPER_FLAG_KEY, 'true');
      localStorage.setItem(AUTO_DEV_UNLOCKED_KEY, 'true');
    }
  } catch (e) {
    console.warn('Storage error saving google user:', e);
  }

  return { isDeveloper: isDev };
}

/**
 * Generates a stable hardware fingerprint hash that persists across app reinstalls
 */
function generateHardwareFingerprint(): number {
  try {
    let fp = '';
    if (typeof screen !== 'undefined') {
      fp += `${screen.width}x${screen.height}x${screen.colorDepth || 24}x${screen.pixelDepth || 24}`;
    }
    if (typeof navigator !== 'undefined') {
      fp += `_${navigator.hardwareConcurrency || 4}_${navigator.maxTouchPoints || 1}_${navigator.platform || ''}`;
    }
    
    // Canvas fingerprinting (deterministic across uninstalls on same hardware)
    if (typeof document !== 'undefined') {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = 200;
        canvas.height = 50;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.textBaseline = 'top';
          ctx.font = '14px Arial';
          ctx.fillStyle = '#06b6d4';
          ctx.fillRect(10, 10, 100, 30);
          ctx.fillStyle = '#f43f5e';
          ctx.fillText('MarinerPro-Hardware-V1', 15, 15);
          fp += `_${canvas.toDataURL().slice(-40)}`;
        }
      } catch {}
    }

    // 32-bit FNV-1a hash
    let hash = 0x811c9dc5;
    for (let i = 0; i < fp.length; i++) {
      hash ^= fp.charCodeAt(i);
      hash = Math.imul(hash, 0x01000193);
    }
    return hash >>> 0;
  } catch {
    return 0x7a9b4f21;
  }
}

/**
 * Generates or retrieves a unique persistent device ID for this phone/browser.
 * Uses hardware fingerprinting so even if the app is reinstalled, the Device ID remains the same.
 */
export function getOrCreateDeviceId(): string {
  try {
    let devId = localStorage.getItem(DEVICE_ID_STORAGE_KEY);
    if (devId && devId.startsWith('MAR-')) {
      return devId;
    }

    const hwHash = generateHardwareFingerprint();
    const part1 = ((hwHash >>> 16) & 0xffff).toString(16).toUpperCase().padStart(4, '0');
    const part2 = (hwHash & 0xffff).toString(16).toUpperCase().padStart(4, '0');
    
    devId = `MAR-${part1}-${part2}`;
    localStorage.setItem(DEVICE_ID_STORAGE_KEY, devId);
    return devId;
  } catch {
    return 'MAR-8A2F-9C14';
  }
}

/**
 * Gets or initializes the First Installation Timestamp (30 Days Trial Clock)
 */
export function getFirstInstallTimestamp(): number {
  try {
    const raw = localStorage.getItem(FIRST_INSTALL_KEY);
    if (raw) {
      const ts = parseInt(raw, 10);
      if (!isNaN(ts) && ts > 1700000000000) {
        return ts;
      }
    }
    
    const now = Date.now();
    localStorage.setItem(FIRST_INSTALL_KEY, now.toString());
    return now;
  } catch {
    return Date.now();
  }
}

/**
 * Calculates the valid Activation Code for a given Device ID.
 * Formula: Deterministic hash on (DeviceID + MASTER_SALT) -> Format: ACT-XXXX-YYYY-ZZZZ
 */
export function generateActivationCode(deviceId: string): string {
  const cleanDevId = deviceId.trim().toUpperCase();
  const input = `${cleanDevId}:${MASTER_SALT}`;
  
  let h1 = 0xdeadbeef;
  let h2 = 0x41c64e6d;
  let h3 = 0x12345678;

  for (let i = 0; i < input.length; i++) {
    const ch = input.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
    h3 = Math.imul(h3 ^ ch, 2246822519);
  }

  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h3 ^ (h3 >>> 13), 3266489909);
  h3 = Math.imul(h3 ^ (h3 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);

  const p1 = (Math.abs(h1) % 0x10000).toString(16).toUpperCase().padStart(4, '0');
  const p2 = (Math.abs(h2) % 0x10000).toString(16).toUpperCase().padStart(4, '0');
  const p3 = (Math.abs(h3) % 0x10000).toString(16).toUpperCase().padStart(4, '0');

  return `ACT-${p1}-${p2}-${p3}`;
}

/**
 * Validates whether an activation key matches the device ID or master bypass passcode
 */
export function verifyActivationCode(deviceId: string, enteredKey: string): boolean {
  if (!enteredKey) return false;
  const cleanKey = enteredKey.trim().toUpperCase().replace(/\s+/g, '');
  
  if (cleanKey === DEVELOPER_PASSCODE || cleanKey === '2450') {
    return true;
  }

  const expectedKey = generateActivationCode(deviceId);
  const cleanExpected = expectedKey.replace(/-/g, '');
  const cleanInput = cleanKey.replace(/-/g, '');

  return cleanKey === expectedKey || cleanInput === cleanExpected;
}

/**
 * Retrieves the complete license & 30-day trial status
 */
export function getLicenseStatus(): LicenseStatus {
  const deviceId = getOrCreateDeviceId();
  const firstInstallTs = getFirstInstallTimestamp();
  const now = Date.now();
  
  const elapsedMs = now - firstInstallTs;
  const remainingMs = TRIAL_DURATION_MS - elapsedMs;
  const daysRemaining = Math.max(0, Math.ceil(remainingMs / (1000 * 60 * 60 * 24)));
  const isTrialExpired = remainingMs <= 0;
  const isTrialActive = !isTrialExpired;

  try {
    const savedKey = localStorage.getItem(LICENSE_STORAGE_KEY);
    if (savedKey && verifyActivationCode(deviceId, savedKey)) {
      return {
        isActivated: true,
        isTrialActive: false,
        isTrialExpired: false,
        daysRemaining: 0,
        trialTotalDays: 30,
        deviceId,
        activatedKey: savedKey,
        firstInstallDate: new Date(firstInstallTs).toLocaleDateString(),
      };
    }
  } catch (err) {
    console.warn('License storage check error:', err);
  }

  return {
    isActivated: false,
    isTrialActive,
    isTrialExpired,
    daysRemaining,
    trialTotalDays: 30,
    deviceId,
    firstInstallDate: new Date(firstInstallTs).toLocaleDateString(),
  };
}

/**
 * Saves and activates the license.
 */
export function activateLicense(enteredKey: string): { success: boolean; message: string } {
  const deviceId = getOrCreateDeviceId();
  if (verifyActivationCode(deviceId, enteredKey)) {
    try {
      const cleanKey = enteredKey.trim().toUpperCase();
      localStorage.setItem(LICENSE_STORAGE_KEY, cleanKey);
      return { success: true, message: 'Software activated successfully.' };
    } catch (err) {
      return { success: false, message: 'Storage error saving license key.' };
    }
  } else {
    return { success: false, message: 'Invalid activation code entered. Please verify and try again.' };
  }
}

/**
 * Checks if Developer Mode (KeyGen Tab) is unlocked.
 */
export function isDeveloperModeUnlocked(): boolean {
  try {
    return localStorage.getItem(DEVELOPER_FLAG_KEY) === 'true';
  } catch {
    return false;
  }
}

/**
 * Unlocks or locks developer mode on this device.
 */
export function setDeveloperMode(enabled: boolean): void {
  try {
    if (enabled) {
      localStorage.setItem(DEVELOPER_FLAG_KEY, 'true');
    } else {
      localStorage.removeItem(DEVELOPER_FLAG_KEY);
    }
  } catch {}
}

/**
 * Resets / deactivates license (useful for testing or re-licensing)
 */
export function deactivateLicense(): void {
  try {
    localStorage.removeItem(LICENSE_STORAGE_KEY);
  } catch {}
}

